kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-samples-olm-operator-edit
  namespace: openshift
subjects:
  - kind: ServiceAccount
    name: openshift-samples-olm-operator
    namespace: samples-olm-operator
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io